services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '5173:5173'
    volumes:
      - ./testownik-web:/app
      - /app/node_modules
    working_dir: /app
    command: pnpm dev --host 0.0.0.0

  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - '8080:80'
